# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/psf/black.git
        rev: stable
        hooks:
            -   id: black
                language_version: python3.8
                files: 'aerie/*'
