# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: ubuntu:20.04
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        strategy:
            matrix:
                python-version: ['3.8']

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install openssl
                run: |
                    apt-get update
                    apt-get install -y --no-install-recommends openssl
            -   name: Install dependencies
                run: |
                    python -m pip install poetry
                    poetry install
            -   name: Test with pytest
                env:
                    key: POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/postgres
                run: |
                    pytest
